apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ufplsjbb
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-ufplsjbb:d718ef64c4119e853216231e0fbd3da488cfa88f@sha256:fb5a424ff693d7fbfa752b6fd83f704ee1f61733c5d69a7b453d657030ac96af
        name: container-image  
